name: Deploy to FTP

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use Node.js 20
        uses: actions/setup-node@master
        with:
          node-version: '20'
      - name: Build SSG
        run: |
          npm install
          npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{secrets.FTP_LOGIN}}
          password: ${{secrets.FTP_PASSWORD}}
          local-dir: ./out/
          server-dir: ./public_html/
          port: 22
          protocol: ftps
          log-level: verbose
